config/routes.rb
require('sidekiq/web')

Rails.application.routes.draw do
  default_url_options host: ENV['ASSET_PATH']
  
  #Sidekiq Routes
  mount Sidekiq::Web => '/sidekiq'
  
  #Swagger Routes
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # Admin Devise Routes
  devise_for :admins, controllers: {
    registrations: 'app/admins/registrations',
    passwords: 'app/admins/passwords',
    confirmations: 'app/admins/confirmations'
  }

  devise_scope :admin do
    authenticated :admin do
      root 'app/dashboards#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # API Routes
  scope '/api' do
    scope '/v1' do
      use_doorkeeper do
        controllers tokens: 'api/v1/tokens'
      end
    end
  end

  scope module: :api, path: 'api' do
    scope module: :v1, path: 'v1' do
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
        passwords: 'api/v1/users/passwords',
        confirmations: 'api/v1/users/confirmations'
      }, scoped_views: 'api/v1/users'
    end
  end

  # APP Routes
  scope module: :app, path: 'app' do
    resource :dashboard, only: [:show]
    resource :additional_payments, only: [:new, :create]
    resources :countries
    resources :cities
    resources :areas
    resources :sub_areas do
      collection do
        get :get_sub_areas
      end
    end
    resources :staffs do
      collection do
        get :archived
        get :check_username
      end
      member do
        get :restore
      end
    end
    resources :payments
    resources :receipt_books do
      collection do
        get :book_pages
      end
    end
    resources :message_templates
    resources :messages
    resources :companies

    resources :purchase_packages do
      collection do
        get :purchase_packages_list
      end
    end
    
    resources :packages do
      collection do
        get :customer_package_list
      end
    end
    resources :customers do 
      collection do
        get :check_username
        get :export_profile
        get :export_billings
      end
      member do
        get :settings
        get :deactivate
        get :activate
      end
      resources :subscriptions do
        collection do
          get :expire
        end
      end
    end
    
    resources :receivings do
      collection do
        get :search_customer
      end
    end
  end

  # root to: 'home#index'
end

app/models/customer.rb
class Customer < ApplicationRecord  
  belongs_to :service, optional: true
  belongs_to :company, optional: true
  belongs_to :purchase_package, optional: true
  belongs_to :package, optional: true
  belongs_to :country, optional: true
  belongs_to :city, optional: true
  belongs_to :area, optional: true
  belongs_to :sub_area, optional: true  
  belongs_to :staff, optional: true  
  belongs_to :internet_type, optional: true
  
  has_many :subscriptions
  has_many :receivings
  has_many :additional_payments

  scope :status, -> { where(status: true) } 
  scope :deactivated, -> { where(status: false) }
  scope :new_customer, -> { where("created_at >= ?", 1.month.ago.utc) }
  scope :subscribed_customer, -> { joins(:subscriptions).where(subscriptions: {status: :subscribed}) }
  scope :expired_subscriptioned_customer, -> { joins(:subscriptions).where(subscriptions: {status: :expired}) }
  
  after_create :sent_welcome_message
  # after_create :start_subscription
  
  def sent_welcome_message
    puts 'Sms service'
    sms = SMSService.new(self.id, self.name, self.mobile_primary)
    response = sms.send_message
    if response == '200'
      puts response      
      self.update_attribute :welcome_message, true
    end
    puts 'done'
  end
  
  def get_package_price
    self.package_discounted_price.nil? ? self.package.price : self.package.price.to_i - self.package_discounted_price.to_i
  end
  
  private
  
  # def start_subscription
  #   self.subscriptions.create!(start_date: Date.today, expiry_date: self.username_expiry, subscription_type: 'Month', status: 'subscribed', profit: get_profit(self) < 0 ? 0 : get_profit(self))
  # end
  
  def get_profit(customer)
    profit = calculate_profit(customer.package.price, customer.purchase_package.purchase_price)
    !customer.package_discounted_price.nil? ? profit - customer.package_discounted_price : profit
  end
  
  def calculate_profit(pp, pppp)
    pp.to_i - pppp.to_i
  end
end

app/controllers/app/customers_controller.rb
module App
  class CustomersController < ApplicationController
    before_action :set_customer, only: %i[edit update show settings activate deactivate]
    
    def index
      @q = Customer.ransack(params[:q])
      filtered_customers(params['filter'], @q) if params['filter'].present?
    end
    
    def new
      @customer = Customer.new      
    end
    
    def create
      @customer = Customer.new(customer_params)
      if @customer.save!        
        redirect_to edit_customer_path(@customer.id), notice: 'Customer Profile was Successfully created'
      else
        render 'new', notice: 'Something went wrong'  
      end
    end
    
    def show; end
    
    def edit; end
     
    def update
      if @customer.update!(customer_params)
        redirect_to edit_customer_path(@customer.id), notice: "Customer was Successfully updated"
      else
        render 'edit', notice: 'Something went wrong';
      end
    end
    
    def check_username
      username = Customer.where(company_id: params['company_id'],
        username: params['username']).any?
      render json: { data: username }
    end
    
    def settings; end
    
    def deactivate
      @customer.update_attribute(:status, false)
      redirect_to settings_customer_path(@customer.id), notice: 'Customer was deactivated successfully.'
    end
    
    def activate
      @customer.update_attribute(:status, true)
      redirect_to settings_customer_path(@customer.id), notice: 'Customer was activated successfully.'    
    end
    
    def export_profile
      @customer = Customer.find_by(id: params['id'])
      respond_to do |format|
        format.xlsx {
          response.headers[
            'Content-Disposition'
          ] = "attachment; filename=customer_profile.xlsx"
        }
        format.html { render :export_profile }
      end
    end
    
    def export_billings
      @customer = Customer.find_by(id: params['id'])
      respond_to do |format|
        format.xlsx {
          response.headers[
            'Content-Disposition'
          ] = "attachment; filename=customer_billings.xlsx"
        }
        format.html { render :export_billings }
      end  
    end
    
    private
    
    def customer_params
      params.require(:customer).permit(:old_ref_no, :name, :father_name, :cnic, :mobile_primary, :mobile_secondary, :service_id, :staff_id, :residance, :welcome_message, :first_receiving, :company_id, :purchase_package_id, :username, :password_text, :package_id, :package_discounted_price,:country_id, :city_id, :area_id, :sub_area_id, :house_no, :pon_no, :address, :remarks,:device_name, :serial_no, :model, :mac_address, :internet_type_id, :joining_date, :username_expiry, :status)
    end
    
    def set_customer
      @customer = Customer.find_by(id: params['id'])
    end
    
    def filtered_customers(filter, q)
      @customers = q.result.status.page(params[:page]).per(25) if filter == 'a' 
      @customers = q.result.new_customer.page(params[:page]).per(25) if filter == 'nc' 
      @customers = q.result.subscribed_customer.page(params[:page]).per(25) if filter == 'sc' 
      @customers = q.result.expired_subscriptioned_customer.page(params[:page]).per(25) if filter == 'exc' 
      @customers = q.result.deactivated.page(params[:page]).per(25) if filter == 'd' 
    end
  end
end

app/helpers/app/customers_helper.rb
module App::CustomersHelper
  def customer_purchase_package(customer)
    customer.purchase_package.purchase_price if request.url.include?('edit')
  end
  
  def customer_package(customer)
    customer.package.price if request.url.include?('edit')
  end
  
  def field_required(customer)
    return true if request.url.include?('new')
  end
  
  def get_subscription_bg(customer)
    if customer&.subscriptions&.count&.zero?
      'transparent_subscription'
    elsif customer&.subscriptions&.last&.subscribed?
      'active_subscription'
    elsif customer&.subscriptions&.last&.expired?
      'expire_subscription'    
    end
  end
end

app/views/app/customers/_area.html.haml
= form_with(model: customer) do |form|
  - if customer.errors.any?
    #error_explanation  
      - customer.errors.full_messages.each do |message|
        .col
          .alert.alert-danger.text-white
            = message
  .card
    .card-header
      %h1.header-title
        Area
    .card-body
      = form.fields_for :customer_area do |customer_area|
        .row
          .col-6                
            .form-group
              = customer_area.label "Country"
              = customer_area.collection_select :country_id, Country.all, :id, :name, {prompt: true, selected: "Pakistan"}, class: "form-control", required: true
          .col-6
            .form-group
              = customer_area.label "City"
              = customer_area.collection_select :city_id, City.all, :id, :name, {prompt: true, selected: "Lahore"}, class: "form-control", required: true
        
        .row
          .col-6                
            .form-group
              = customer_area.label "Area"
              = customer_area.collection_select :area_id, Area.all, :id, :name, {prompt: true}, class: "form-control", required: true
          .col-6                  
            .form-group
              = customer_area.label "Sub Area"
              = customer_area.collection_select :sub_area_id, SubArea.all, :id, :name, {prompt: true}, class: "form-control", required: true
        
        .row
          .col-6
            .form-group
              = customer_area.label "House No"
              = customer_area.text_field :house_no, class: "form-control", placeholder: "Enter House No"
            
          .col-6
            .form-group
              = customer_area.label "PON No"
              = customer_area.text_field :pon_no, class: "form-control", placeholder: "Enter Pon No"
            
        
        .row
          .col-12 
            .form-group
              = customer_area.label "Address"
              = customer_area.text_area :address, class: "form-control", placeholder: "Enter Adress"
            
        .row 
          .col-12   
            .form-group
              = customer_area.label "Remarks"
              = customer_area.text_area :remarks, class: "form-control", placeholder: "Add Remarks" 
    .card-footer
      .actions
        = form.submit "Submit Area", class: "btn btn-primary"       

app/views/app/customers/_area_view.html.haml
.card
  .card-body
    .list-group.list-group-flush
      .list-group-item
        .row.align-items-center
          .col
            %h1.header-title
              Area
          
    .list-group.list-group-flush
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Country
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.country&.name
      / / .row
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small City
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.city&.name
              
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Area
          .col-auto
            / Text
            %small.text-muted
              = customer&.area&.name
        / / .row
        
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Sub Area
          .col-auto
            / Text
            %small.text-muted
              = customer&.country&.name
        / / .row
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small House No
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.house_no
      
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Pon No
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.pon_no
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Address
          .col-auto
            / Time
            %time.small.text-muted{:datetime => "1988-10-24"}
              = customer&.address
        / / .row
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Remarks
          .col-auto
            / Text
            %small.text-muted
              = customer&.remarks
        

app/views/app/customers/_device_info.html.haml
= form_with(model: customer) do |form|
  - if customer.errors.any?
    #error_explanation  
      - customer.errors.full_messages.each do |message|
        .col
          .alert.alert-danger.text-white
            = message
  .card
    .card-header
      %h1.header-title
        Device Info
    .card-body
      = form.fields_for :customer_device_info do |customer_device|
        .row
          .col-12
            .form-group
              = customer_device.label "Device Name"
              = customer_device.text_field :device_name, class: "form-control", placeholder: "Enter Device Name"
          
        .row
          .col-12
            .form-group
              = customer_device.label "Serial No"
              = customer_device.text_field :serial_no, class: "form-control", placeholder: "Enter Serial No"
       
        .row
          .col-12
            .form-group
              = customer_device.label "Model"
              = customer_device.text_field :model, class: "form-control", placeholder: "Enter Model"
          
        .row
          .col-12
            .form-group
              = customer_device.label "Mac Address"
              = customer_device.text_field :mac_address, class: "form-control", placeholder: "Enter Mac Address"       
        
    .card-footer
      .actions
        = form.submit "Submit Device Info", class: "btn btn-primary"       

app/views/app/customers/_form.html.haml
.row
  .col
  = render "profile", customer: customer  
  -# .col-sm-3
  -#   .card
  -#     .card-body.p-0
  -#       %ul.list-group     
  -#         %li.list-group-item{class: ('active' if params['step'] == 'profile')}
  -#           = link_to 'Profile', "?step=profile", class: "#{params['step'] == 'profile' ? 'text-white' : 'text-dark'}"  
          
  -#         - if request.fullpath.include?('edit')
  -#           %li.list-group-item{class: ('active' if params['step'] == 'area')} 
  -#             = link_to 'Area', '?step=area', class: "#{params['step'] == 'area' ? 'text-white' : 'text-dark'}"
            
  -#           %li.list-group-item{class: ('active' if params['step'] == 'subscription')} 
  -#             = link_to 'Subscription', '?step=subscription', class: "#{params['step'] == 'subscription' ? 'text-white' : 'text-dark'}"  
            
  -#           %li.list-group-item{class: ('active' if params['step'] == 'device_info')} 
  -#             = link_to 'Device Info', '?step=device_info', class: "#{params['step'] == 'device_info' ? 'text-white' : 'text-dark'}"
            
  -#           %li.list-group-item{class: ('active' if params['step'] == 'assign_to_staff')} 
  -#             = link_to 'Assign To Staff', '?step=assign_to_staff', class: "#{params['step'] == 'assign_to_staff' ? 'text-white' : 'text-dark'}"      
    
  -# .col-sm-9
  -#   - if params['step'] == 'profile'
  -#     = render "profile", customer: customer
  -#   - elsif params['step'] == 'area'
  -#     = render "area", customer: customer
  -#   - elsif params['step'] == 'subscription'
  -#     = render "subscription", customer: customer
  -#   - elsif params['step'] == 'device_info'
  -#     = render "device_info", customer: customer
  -#   - elsif params['step'] == 'assign_to_staff'
  -#     = render "staff", customer: customer           

app/views/app/customers/_package.html.haml
- if customer.service
  = form_with(model: customer) do |form|
    - if customer.errors.any?
      #error_explanation  
        - customer.errors.full_messages.each do |message|
          .col
            .alert.alert-danger.text-white
              = message
    .card
      .card-header
        %h1.header-title
          Package
      .card-body 
        = form.fields_for :customer_package do |customer_package|     
          .row
            
          
          
                
          
        
        
      .card-footer
        .actions
          = form.submit "Submit Package", class: "btn btn-primary", id: "submit_button"
- else
  .row
    .col-12
      / Card
      .card.card-inactive
        .card-body.text-center
          / Image
          %img.img-fluid{:alt => "...", :src => "/img/scale.svg", :style => "max-width: 182px;"}/
          / Title
          %h1
            Empty Service.
          / Subtitle
          %p.text-muted
            Please select service from the upper menu.                     

app/views/app/customers/_package_view.html.haml
.card
  .card-body
    .list-group.list-group-flush
      .list-group-item
        .row.align-items-center
          .col
            %h1.header-title
              Package
          
    .list-group.list-group-flush
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Company
          .col-auto
            / Text
            %small.text-muted
              = customer&.company&.name
              
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Username
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.username
      
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Passsword
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.password_text
      
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Purchase Package Name
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.purchase_package&.package_name
      
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Purchase Package Price
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.purchase_package&.purchase_price
                              
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Selling Package Name
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.package&.name        
      / / .row
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Selling Package Price
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.package&.price
      
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Selling Dicounted Price
          .col-auto
            / Text
            %small.text-muted
              = customer&.package_discounted_price || 0        

app/views/app/customers/_search.html.haml
= search_form_for q do |f|
  .input-group.input-group-flush.input-group-merge.input-group-reverse
    = f.search_field :name_or_username_or_mobile_primary_or_area_name_or_sub_area_name_or_company_name_or_package_name_or_service_name_or_staff_full_name_cont, class: 'form-control list-search', placeholder: 'Search'
    %span.input-group-text
      %i.fe.fe-search                    

app/views/app/customers/_service.html.haml
= form_with(model: customer) do |form|
  - if customer.errors.any?
    #error_explanation  
      - customer.errors.full_messages.each do |message|
        .col
          .alert.alert-danger.text-white
            = message
  .card
    .card-header
      %h1.header-title
        Service
    .card-body 
      .row
        
    -# .card-footer
    -#   .actions
    -#     = form.submit "Select Service", class: "btn btn-primary"         

app/views/app/customers/_staff.html.haml
= form_with(model: customer) do |form|
  - if customer.errors.any?
    #error_explanation  
      - customer.errors.full_messages.each do |message|
        .col
          .alert.alert-danger.text-white
            = message
  .card
    .card-header
      %h1.header-title
        Assign To Staff
    .card-body
      .row
        .col-12                
          .form-group
            = form.label "Staff"
            = form.collection_select :staff_id, Staff.all, :id, :full_name, {prompt: true}, class: "form-control"
    .card-footer
      .actions
        = form.submit "Submit", class: "btn btn-primary"                 

app/views/app/customers/_subscription.html.haml
- if !customer.username.nil?
  = form_with(model: customer) do |form|
    - if customer.errors.any?
      #error_explanation  
        - customer.errors.full_messages.each do |message|
          .col
            .alert.alert-danger.text-white
              = message
    .card
      .card-header
        %h1.header-title
          Subscription
      .card-body
        = form.fields_for :subscription do |subscription|
          .row
            .col-sm-6                
              .form-group
                = label_tag "Customer Package" 
                = text_field_tag "customer_package", "#{customer.package.name}", class: "form-control readonly_field", readonly: true
            .col-sm-6                
              .form-group
                = label_tag "Customer Package Price" 
                = text_field_tag "customer_package_price", "#{customer.get_package_price}", class: "form-control readonly_field", readonly: true
          .row
            .col-sm-12                
              .form-group
                = subscription.label "Subscription Type" 
                = subscription.select :subscription_type, [["Daily", "daily"], ["Monthly", "monthly"]], {prompt: "Select Type"}, { class: 'form-control', required: true}
          .according-to-type
            .row  
              .col-sm-12                
                .form-group
                  = subscription.label "Start Date" 
                  = subscription.date_field :start_date, class: "form-control", required: true
            
            .row  
              .col-sm-12                
                .form-group
                  = subscription.label "No of Days" 
                  = subscription.number_field :no_of_days, class: "form-control"
            
            .row  
              .col-sm-12                
                .form-group
                  = subscription.label "Expiry Date" 
                  = subscription.date_field :expiry_date, class: "form-control", required: true

            
            -# .row
            -#   .col-12               
            -#     .form-group
            -#       .form-check.form-switch
            -#         = subscription.check_box :renew, class: "form-check-input", id: "flexSwitchCheckDefault"
            -#         %label.form-check-label{for: "flexSwitchCheckDefault"} Renew (This will auto renew subscription) 
          

      .card-footer
        .actions
          - if !customer&.subscriptions&.last&.status
            = form.submit "Subscribe", class: "btn btn-primary"
          - else
            = link_to 'Un Subscribe', "#", class: "btn btn-danger btn-lg"
-# - else
-#   .row
-#     .col-12
-#       / Card
-#       .card.card-inactive
-#         .card-body.text-center
-#           / Image
-#           %img.img-fluid{:alt => "...", :src => "/img/scale.svg", :style => "max-width: 182px;"}/
-#           / Title
-#           %h1
-#             Empty Package.
-#           / Subtitle
-#           %p.text-muted
-#             Please fill all values of package to subscribe the package.                     

app/views/app/customers/_subscription_view.html.haml
.card
  .card-body
    .list-group.list-group-flush
      .list-group-item
        .row.align-items-center
          .col
            %h1.header-title
              Subscription
          
    .list-group.list-group-flush
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Country
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.customer_area&.country&.name
      / / .row
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small City
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.customer_area&.city&.name
              
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Area
          .col-auto
            / Text
            %small.text-muted
              = customer&.customer_area&.area&.name
        / / .row
        
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Sub Area
          .col-auto
            / Text
            %small.text-muted
              = customer&.customer_area&.country&.name
        / / .row
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small House No
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.customer_area&.house_no
      
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Pon No
          .col-auto
            / Link
            %a.small.text-muted
              = customer&.customer_area&.pon_no
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Address
          .col-auto
            / Time
            %time.small.text-muted{:datetime => "1988-10-24"}
              = customer&.customer_area&.address
        / / .row
      .list-group-item
        .row.align-items-center
          .col
            / Title
            %small Remarks
          .col-auto
            / Text
            %small.text-muted
              = customer&.customer_area&.remarks
        

app/views/app/customers/edit.html.haml
.header
  .container-fluid
    .header-body
      .row.align-items-end
        .col
          %h6.header-pretitle
            Overview
          %h1.header-title
            Edit Customer
        .col-auto
          - if @customer.first_receiving == false 
            - if @customer.additional_payments.present?
              = link_to 'Receive First Payment', "#{new_receiving_path}?customer_id=#{@customer.id}&term=first" , class: "btn btn-danger lift"
            - else 
              = link_to 'Receive First Payment', '', class: 'btn btn-danger lift', id: 'additional', data: { customer_id: @customer.id }
          - if @customer.welcome_message == false  
            = link_to 'Sent Welcome Message', "#{new_message_path}?number=#{@customer.mobile_primary}", class: "btn btn-success lift"
.container-fluid   
  = render 'form', customer: @customer
             

app/views/app/customers/settings.html.haml
.header
  .container-fluid
    .header-body
      .row.align-items-end
        .col
          %h6.header-pretitle
            Overview
          %h1.header-title
            Customer Settings
              

.container-fluid   
  .row.justify-content-center
    .col-12.col-lg-10.col-xl-8
      
      .row
        .col-sm-4 
          = render "/app/customers/profile_view", customer: @customer
        .col-sm-8
          .card.customer-data-download
            .card-header
              %h1.header-title
                Export Customer Data
            .card-body
              .row.align-items-center
                .col
                  %h2.mb-0
                    Profile                  
                .col-auto
                  -# = link_to 'PDF', '#', class: "btn btn-outline-warning btn-sm lift"         
                  = link_to 'Excel', "#{export_profile_customers_path(format: :xlsx)}?id=#{@customer.id}", class: "btn btn-outline-success btn-sm lift"
              
              %hr
              .row.align-items-center
                .col
                  %h2.mb-0
                    Billings                  
                .col-auto
                  = link_to 'Excel', "#{export_billings_customers_path(format: :xlsx)}?id=#{@customer.id}", class: "btn btn-outline-success btn-sm lift"
              
              %hr                   
              .row.align-items-center
                .col
                  %h2.mb-0
                    Subscriptions                  
                .col-auto
                  = link_to 'Excel', '#', class: "btn btn-outline-success btn-sm lift"
              
              %hr                   
              .row.align-items-center
                .col
                  %h2.mb-0
                    All                  
                .col-auto
                  = link_to 'Excel', '#', class: "btn btn-outline-success btn-sm lift"
                   
      .card.danger-zone-border
        .card-header
          %h1.header-title
            Danger Zone
        .card-body
          .row.align-items-center
            .col
              %h2.mb-0
                Expire Subscrption
              %span.text-muted
                Forcefully Expire Subscription                  
            .col-auto
              - if @customer.subscriptions.any? && @customer.subscriptions.last.subscribed?
                = link_to 'Expire Subscription', expire_customer_subscriptions_path(@customer.id), class: "btn btn-danger btn-lg lift",  data: {confirm: 'Are you sure to expire subscription?'}
              - else
                = link_to 'Expire Subscription', "#", class: "btn btn-outline-danger btn-lg lift", disabled: true
          %hr
          
          .row.align-items-center
            .col
              %h2.mb-0
                Remove Username
              %span.text-muted
                Remove username of this Customer
            .col-auto
              = link_to 'Remove Username', '#', class: "btn btn-outline-danger btn-lg lift"
         
          %hr
            
            .row.align-items-center
              .col
                %h2.mb-0
                  Deactivate Customer
              .col-auto
                - if @customer.status
                  = link_to 'Deactivate', deactivate_customer_path(@customer.id), class: "btn btn-outline-danger btn-lg lift",  data: {confirm: 'Are you sure to deactivate customer?'}
                - else 
                  = link_to 'Activate', activate_customer_path(@customer.id), class: "btn btn-success btn-lg lift",  data: {confirm: 'Are you sure to activate customer?'}
                  
          %hr
            
            .row.align-items-center
              .col
                %h2.mb-0
                  Delete Customer
                %span.text-muted
                  This will permanantly delete customer with all its data.  
              .col-auto
                = link_to 'Delete', '#', class: "btn btn-outline-danger btn-lg lift"                  