config/routes.rb
require('sidekiq/web')

Rails.application.routes.draw do
  default_url_options host: ENV['ASSET_PATH']
  
  #Sidekiq Routes
  mount Sidekiq::Web => '/sidekiq'
  
  #Swagger Routes
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # Admin Devise Routes
  devise_for :admins, controllers: {
    registrations: 'app/admins/registrations',
    passwords: 'app/admins/passwords',
    confirmations: 'app/admins/confirmations'
  }

  devise_scope :admin do
    authenticated :admin do
      root 'app/dashboards#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # API Routes
  scope '/api' do
    scope '/v1' do
      use_doorkeeper do
        controllers tokens: 'api/v1/tokens'
      end
    end
  end

  scope module: :api, path: 'api' do
    scope module: :v1, path: 'v1' do
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
        passwords: 'api/v1/users/passwords',
        confirmations: 'api/v1/users/confirmations'
      }, scoped_views: 'api/v1/users'
    end
  end

  # APP Routes
  scope module: :app, path: 'app' do
    resource :dashboard, only: [:show]
    resource :additional_payments, only: [:new, :create]
    resources :countries
    resources :cities
    resources :areas
    resources :sub_areas do
      collection do
        get :get_sub_areas
      end
    end
    resources :staffs do
      collection do
        get :archived
        get :check_username
      end
      member do
        get :restore
      end
    end
    resources :payments
    resources :receipt_books do
      collection do
        get :book_pages
      end
    end
    resources :message_templates
    resources :messages
    resources :companies

    resources :purchase_packages do
      collection do
        get :purchase_packages_list
      end
    end
    
    resources :packages do
      collection do
        get :customer_package_list
      end
    end
    resources :customers do 
      collection do
        get :check_username
        get :export_profile
        get :export_billings
      end
      member do
        get :settings
        get :deactivate
        get :activate
      end
      resources :subscriptions do
        collection do
          get :expire
        end
      end
    end
    
    resources :receivings do
      collection do
        get :search_customer
      end
    end
  end

  # root to: 'home#index'
end

app/views/shared/_admin_nav.html.haml
%ul.navbar-nav
  %li.nav-item
    = active_link_to dashboard_path, class: "nav-link" do
      %img.icon-size{:alt => "...", :src => "/img/icons/speedometer.png"}
      &nbsp&nbspDashboard
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarCountry", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarCountry", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/google-maps.png"}
      &nbsp&nbspArea 
    #sidebarCountry.collapse{class: ("show" if request.fullpath.include?('app/countries') || request.fullpath.include?('app/cities') || request.fullpath.include?('app/areas')  || request.fullpath.include?('app/sub_areas'))}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to countries_path, class: "nav-link" do
            Countries
        %li.nav-item
          = active_link_to cities_path, class: "nav-link" do
            Cities
        %li.nav-item
          = active_link_to areas_path, class: "nav-link" do
            Areas            
        %li.nav-item
          = active_link_to sub_areas_path, class: "nav-link" do
            Sub Areas
    
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarStaff", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarStaff", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/staff.png"}
      &nbsp&nbspStaff 
    #sidebarStaff.collapse{class: ("show" if request.fullpath.include?('app/staffs') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to staffs_path, class: "nav-link" do
            Staffs
        %li.nav-item
          = active_link_to archived_staffs_path, class: "nav-link" do
            Archived                
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarPayment", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarPayment", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/money.png"}
      &nbsp&nbspPayment 
    #sidebarPayment.collapse{class: ("show" if request.fullpath.include?('app/payments') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to payments_path, class: "nav-link" do
            Payments
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarBook", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarBook", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/contract.png"}
      &nbsp&nbspReceipt Book 
    #sidebarBook.collapse{class: ("show" if request.fullpath.include?('app/receipt_books') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to receipt_books_path, class: "nav-link" do
            Receipt Books                    
    
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarCompany", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarCompany", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/company.png"}
      &nbsp&nbspCompany 
    #sidebarCompany.collapse{class: ("show" if request.fullpath.include?('app/companies') || request.fullpath.include?('app/company_packages') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to companies_path, class: "nav-link" do
            Companies
        %li.nav-item
          = active_link_to company_packages_path, class: "nav-link" do
            Packages
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarPackage", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarPackage", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/package.png"}
      &nbsp&nbspPackage 
    #sidebarPackage.collapse{class: ("show" if request.fullpath.include?('app/packages') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to packages_path, class: "nav-link" do
            Customer Packages
  
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarCustomer", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarCustomer", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/customer.png"}
      &nbsp&nbspCustomer 
    #sidebarCustomer.collapse{class: ("show" if request.fullpath.include?('app/customers') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to customers_path, class: "nav-link" do
            Customers                                  
   
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarReceiving", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarReceiving", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/receiving.png"}
      &nbsp&nbspReceiving 
    #sidebarReceiving.collapse{class: ("show" if request.fullpath.include?('app/receivings') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to receivings_path, class: "nav-link" do
            Receivings
   
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarSMS", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarSMS", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/sms.png"}
      &nbsp&nbspMessage 
    #sidebarSMS.collapse{class: ("show" if request.fullpath.include?('app/message_templates') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to message_templates_path, class: "nav-link" do
            Templates         
        %li.nav-item
          = active_link_to new_message_path, class: "nav-link" do
            New Message         

app/views/shared/_flash_messages.html.erb
<% if !flash.empty? %>
  <% flash.each do |key, value| %>
    <script>
      var value = '<%=value%>';
      var key = '<%=key%>';
      var type;

      if (key == "notice")
        type = "success";
      else if (key == "alert")
        type = "error";
      else
        type = "info";

      new Noty({
        type: type,
        layout: 'topCenter',
        theme: 'relax',
        text: value,
        timeout: '2000',
        closeWith: ['click']
      }).show();

    </script>
  <% end %>
  <% flash.clear %>
<% end %>

app/views/shared/_header.html.haml
%nav#topbar.navbar.navbar-expand-md.navbar-light.d-none.d-md-flex
  .container-fluid
    .mr-4.d-none.d-md-flex
    .navbar-user
      .dropdown
        %a.avatar.avatar-sm.avatar-online.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
          %img.avatar-img.rounded-circle{alt: "...", src: "/img/icons/project-manager.png"}/
        .dropdown-menu.dropdown-menu-end
          %a.dropdown-item{href: "javascript:void(0)"} Profile
          = link_to "Settings",edit_admin_registration_path, class: "dropdown-item"
          %hr.dropdown-divider/
          = button_to "Sign out", destroy_admin_session_path, method: :delete, class: "dropdown-item"
          

app/views/shared/_no_data.html.erb
<div class="row">
  <div class="col-12">
    
    <!-- Card -->
    <div class="card card-inactive">
      <div class="card-body text-center">

        <!-- Image -->
        <img src="/img/scale.svg" alt="..." class="img-fluid" style="max-width: 182px;">
        
        <!-- Title -->
        <h1>
          No data yet.
        </h1>

        <!-- Subtitle -->
        <p class="text-muted">
          Create a new record, click on New button top right.
        </p>

      </div>
    </div>

  </div>
</div> <!-- / .row -->

app/views/shared/_sidebar.html.haml
%nav#sidebar.navbar.navbar-vertical.fixed-start.navbar-expand-md.navbar-light
  .container-fluid
    / Toggler
    %button.navbar-toggler{"aria-controls" => "sidebarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#sidebarCollapse", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    / Brand
    %a.navbar-brand{:href => dashboard_path}
      %img.navbar-brand-img.mx-auto{:alt => "...", :src => "/img/logo.svg"}/
    / User (xs)
    .navbar-user.d-md-none
      / Dropdown
      .dropdown
        / Toggle
        %a#sidebarIcon.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", href: "#", role: "button"}
          .avatar.avatar-sm.avatar-online
            %img.avatar-img.rounded-circle{alt: "...", src: "/img/avatars/profiles/avatar.png"}/
        / Menu
        .dropdown-menu.dropdown-menu-end{"aria-labelledby" => "sidebarIcon"}
          %a.dropdown-item{href: "javascript:void(0)"} Profile
          %a.dropdown-item{href: "javascript:void(0)"} Settings
          %hr.dropdown-divider/
          = link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item"
    / Collapse
    #sidebarCollapse.collapse.navbar-collapse
      / Navigation
      - if current_admin.has_role? :super_admin
        = render "shared/super_admin_nav"
      - elsif current_admin.has_role? :admin
        = render "shared/admin_nav"
      - elsif current_admin.has_role? :staff
        = render "shared/staff_nav"  
      .mt-auto
    / / .navbar-collapse

app/views/shared/_staff_nav.html.haml
%ul.navbar-nav
  %li.nav-item
    = active_link_to dashboard_path, class: "nav-link" do
      %img.icon-size{:alt => "...", :src => "/img/icons/speedometer.png"}
      &nbsp&nbspDashboard
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarCustomer", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarCustomer", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/customer.png"}
      &nbsp&nbspCustomer 
    #sidebarCustomer.collapse{class: ("show" if request.fullpath.include?('app/customers') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to "#{customers_path}?filter=a", class: "nav-link" do
            Customers                                 
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarReceiving", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarReceiving", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/receiving.png"}
      &nbsp&nbspReceiving 
    #sidebarReceiving.collapse{class: ("show" if request.fullpath.include?('app/receivings') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to receivings_path, class: "nav-link" do
            Receivings
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarBook", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarBook", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/contract.png"}
      &nbsp&nbspReceipt Book 
    #sidebarBook.collapse{class: ("show" if request.fullpath.include?('app/receipt_books') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to receipt_books_path, class: "nav-link" do
            Receipt Books          
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarCountry", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarCountry", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/google-maps.png"}
      &nbsp&nbspArea 
    #sidebarCountry.collapse{class: ("show" if request.fullpath.include?('app/countries') || request.fullpath.include?('app/cities') || request.fullpath.include?('app/areas')  || request.fullpath.include?('app/sub_areas'))}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to areas_path, class: "nav-link" do
            Areas            
        %li.nav-item
          = active_link_to sub_areas_path, class: "nav-link" do
            Sub Areas
    
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarStaff", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarStaff", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/staff.png"}
      &nbsp&nbspStaff 
    #sidebarStaff.collapse{class: ("show" if request.fullpath.include?('app/staffs') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to staffs_path, class: "nav-link" do
            Staffs
                        
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarPayment", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarPayment", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/money.png"}
      &nbsp&nbspPayment 
    #sidebarPayment.collapse{class: ("show" if request.fullpath.include?('app/payments') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to payments_path, class: "nav-link" do
            Payments
          

app/views/shared/_super_admin_nav.html.haml
%ul.navbar-nav
  %li.nav-item
    = active_link_to dashboard_path, class: "nav-link" do
      %img.icon-size{:alt => "...", :src => "/img/icons/speedometer.png"}
      &nbsp&nbspDashboard
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarCustomer", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarCustomer", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/customer.png"}
      &nbsp&nbspCustomer 
    #sidebarCustomer.collapse{class: ("show" if request.fullpath.include?('app/customers') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to "#{customers_path}?filter=a", class: "nav-link" do
            Customers                                 
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarReceiving", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarReceiving", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/receiving.png"}
      &nbsp&nbspReceiving 
    #sidebarReceiving.collapse{class: ("show" if request.fullpath.include?('app/receivings') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to receivings_path, class: "nav-link" do
            Receivings
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarBook", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarBook", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/contract.png"}
      &nbsp&nbspReceipt Book 
    #sidebarBook.collapse{class: ("show" if request.fullpath.include?('app/receipt_books') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to receipt_books_path, class: "nav-link" do
            Receipt Books          
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarCountry", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarCountry", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/google-maps.png"}
      &nbsp&nbspArea 
    #sidebarCountry.collapse{class: ("show" if request.fullpath.include?('app/countries') || request.fullpath.include?('app/cities') || request.fullpath.include?('app/areas')  || request.fullpath.include?('app/sub_areas'))}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to countries_path, class: "nav-link" do
            Countries
        %li.nav-item
          = active_link_to cities_path, class: "nav-link" do
            Cities
        %li.nav-item
          = active_link_to areas_path, class: "nav-link" do
            Areas            
        %li.nav-item
          = active_link_to sub_areas_path, class: "nav-link" do
            Sub Areas
    
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarStaff", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarStaff", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/staff.png"}
      &nbsp&nbspStaff 
    #sidebarStaff.collapse{class: ("show" if request.fullpath.include?('app/staffs') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to staffs_path, class: "nav-link" do
            Staffs
        %li.nav-item
          = active_link_to archived_staffs_path, class: "nav-link" do
            Archived                
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarPayment", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarPayment", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/money.png"}
      &nbsp&nbspPayment 
    #sidebarPayment.collapse{class: ("show" if request.fullpath.include?('app/payments') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to payments_path, class: "nav-link" do
            Payments
  
                      
    
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarCompany", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarCompany", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/company.png"}
      &nbsp&nbspCompany 
    #sidebarCompany.collapse{class: ("show" if request.fullpath.include?('app/companies') || request.fullpath.include?('app/purchase_packages') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to companies_path, class: "nav-link" do
            Companies
        %li.nav-item
          = active_link_to purchase_packages_path, class: "nav-link" do
            Purchase Packages
  
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarPackage", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarPackage", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/package.png"}
      &nbsp&nbspSell Packages 
    #sidebarPackage.collapse{class: ("show" if request.fullpath.include?('app/packages') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to packages_path, class: "nav-link" do
            Customer Packages
  
  
   
   
  
   
  %li.nav-item
    %a.nav-link{"aria-controls" => "sidebarSMS", "aria-expanded" => "false", "data-bs-toggle" => "collapse", href: "#sidebarSMS", role: "button"}
      %img.icon-size{:alt => "...", :src => "/img/icons/sms.png"}
      &nbsp&nbspMessage 
    #sidebarSMS.collapse{class: ("show" if request.fullpath.include?('app/message_templates') )}
      %ul.nav.nav-sm.flex-column
        %li.nav-item
          = active_link_to message_templates_path, class: "nav-link" do
            Templates         
        %li.nav-item
          = active_link_to new_message_path, class: "nav-link" do
            New Message         