config/routes.rb
require('sidekiq/web')

Rails.application.routes.draw do
  default_url_options host: ENV['ASSET_PATH']
  
  #Sidekiq Routes
  mount Sidekiq::Web => '/sidekiq'
  
  #Swagger Routes
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # Admin Devise Routes
  devise_for :admins, controllers: {
    registrations: 'app/admins/registrations',
    passwords: 'app/admins/passwords',
    confirmations: 'app/admins/confirmations'
  }

  devise_scope :admin do
    authenticated :admin do
      root 'app/dashboards#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # API Routes
  scope '/api' do
    scope '/v1' do
      use_doorkeeper do
        controllers tokens: 'api/v1/tokens'
      end
    end
  end

  scope module: :api, path: 'api' do
    scope module: :v1, path: 'v1' do
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
        passwords: 'api/v1/users/passwords',
        confirmations: 'api/v1/users/confirmations'
      }, scoped_views: 'api/v1/users'
    end
  end

  # APP Routes
  scope module: :app, path: 'app' do
    resource :dashboard, only: [:show]
    resource :additional_payments, only: [:new, :create]
    resources :countries
    resources :cities
    resources :areas
    resources :sub_areas do
      collection do
        get :get_sub_areas
      end
    end
    resources :staffs do
      collection do
        get :archived
        get :check_username
      end
      member do
        get :restore
      end
    end
    resources :payments
    resources :receipt_books do
      collection do
        get :book_pages
      end
    end
    resources :message_templates
    resources :messages
    resources :companies

    resources :purchase_packages do
      collection do
        get :purchase_packages_list
      end
    end
    
    resources :packages do
      collection do
        get :customer_package_list
      end
    end
    resources :customers do 
      collection do
        get :check_username
        get :export_profile
        get :export_billings
      end
      member do
        get :settings
        get :deactivate
        get :activate
      end
      resources :subscriptions do
        collection do
          get :expire
        end
      end
    end
    
    resources :receivings do
      collection do
        get :search_customer
      end
    end
  end

  # root to: 'home#index'
end

app/models/receiving.rb
class Receiving < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :staff, optional: true
  belongs_to :receipt_book, optional: true
  belongs_to :receipt_book_page, optional: true
  
  after_create :add_bill
  after_create :update_customer
  
  def add_bill
    receipt_book_page = ReceiptBookPage.find_by(id: self.receipt_book_page_id)
    receipt_book_page.update_attribute(:amount, self.amount_received);
  end
  
  def update_customer
    customer = Customer.find_by(id: self.customer_id)
    customer.update_attribute :first_receiving, true
  end
end

app/controllers/app/receivings_controller.rb
module App
  class ReceivingsController < ApplicationController
    def index
      @q = Receiving.ransack(params[:q])
      @receivings = @q.result.page(params[:page]).per(10)
    end
    
    def search_customer
      @q = Customer.ransack(params[:q])
      @customers = @q.result
    end
    
    def new
      @receiving = Receiving.new
      if params['customer_id'].present?
        customer = Customer.find_by(id: params['customer_id'])
        if customer
          @customer = customer
        else
          redirect_to request.referrer, alert: 'Customer Not Found' 
        end
      end
    end
    
    def create
      @receiving = Receiving.new(receiving_params)
      if @receiving.save!
        redirect_to receivings_path, notice: 'Receivng was Successfully created'
      else
        
        render 'new', notice: 'Something went wrong'  
      end
    end
    
    private
    
    def receiving_params
      params.require(:receiving).permit(:customer_id, :staff_id, :amount, :service, :receipt_book_id, :receipt_book_page_id, :receiving_date, :balance, :amount_received, :discount, :status)
    end
  end
end

app/helpers/app/receivings_helper.rb
module App::ReceivingsHelper
end

app/views/app/receivings/_customer_billing.html.haml
.card.mt-5
  .card-header
    %h1.header-title
      Last 6 Month's Billing
  .table-responsive
    %table.table.table-sm.table-nowrap.card-table
      - if customer.receivings.any?
        %thead
          %tr
            %th #
            %th Staff
            %th Customer
            %th Fee Month
            %th Amount
            %th Receiving Date
            %th Book No
            %th Receipt Page No 
            %th Received Amount
            %th Remaining
        %tbody.list
          - customer.receivings.last(6).each.with_index(1) do |receiving, index|
            %tr
              %td= index
              %td= receiving.staff.full_name
              %td= receiving.customer.name
              %td= receiving.receiving_date.strftime("%B")
              %td= receiving.amount
              %td= receiving.receiving_date
              %td= receiving.receipt_book.book_number
              %td= receiving.receipt_book_page.page_no
              %td= receiving.amount_received
              %td= receiving.balance
      - else
        = render 'shared/no_data'

app/views/app/receivings/_form.html.haml
= form_with(model: receiving) do |form|
  - if receiving.errors.any?
    #error_explanation  
      - receiving.errors.full_messages.each do |message|
        .col
          .alert.alert-danger.text-white
            = message
  -# = render "customer_search", form: form
  
  .row
    .col-sm-12
      - if customer
        / List group
        
        .row
          .col-6
            .card.custom-card
              .card-body.custom-card-body
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Customer ID:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.id
              
          .col-6            
            .card.custom-card
              .card-body.custom-card-body
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Customer Old ID:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.old_ref_no || 'N/A'
          
        .row
          .col-6
            .card.custom-card
              .card-body.custom-card-body         
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Customer Name:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.name
              
          .col-6  
            .card.custom-card
              .card-body.custom-card-body
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Area:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.area&.name
        
        .row
          .col-6
            .card.custom-card
              .card-body.custom-card-body
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Sub Area:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.sub_area&.name
                
                      
          .col-6
            .card.custom-card
              .card-body.custom-card-body      
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small House #:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.house_no  
        
        .row
          .col-6
            .card.custom-card
              .card-body.custom-card-body      
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Address:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.address
                      
          .col-6
            .card.custom-card
              .card-body.custom-card-body                           
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Pon No:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.pon_no
        .row
          .col-6
            .card.custom-card
              .card-body.custom-card-body                           
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Mobile:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.mobile_primary
                
                                  
          .col-6
            .card.custom-card
              .card-body.custom-card-body                           
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Company:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.company&.name
                
        .row
          .col-6
            .card.custom-card
              .card-body.custom-card-body                           
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Customer Package:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.package&.name                              
                    
          .col-6      
            .card.custom-card
              .card-body.custom-card-body                           
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Purchase Package:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.purchase_package&.package_name
                
        .row
          .col-6
            .card.custom-card
              .card-body.custom-card-body                           
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Username:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = customer&.username        
          .col-6      
            .card.custom-card
              .card-body.custom-card-body
                - if @customer&.service&.name == 'Internet'
                  .list-group.list-group-flush
                    .list-group-item
                      .row.align-items-center
                        .col
                          / Title
                          %small Customer Type:
                        .col-auto
                          / Time
                          %time.small.text-muted
                            = customer&.internet_type&.name                      
            
        .row
          .col-6
            .card.custom-card
              .card-body.custom-card-body                           
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col
                        / Title
                        %small Billing Cycle:
                      .col-auto
                        / Time
                        %time.small.text-muted
                          = "( #{customer&.receivings&.where(status: false).count} / #{customer&.receivings&.where(status: true).count} )"        
          .col-6
            .card.custom-card
              .card-body.custom-card-body.bg-success-soft                           
                .list-group.list-group-flush
                  .list-group-item
                    .row.align-items-center
                      .col.text-center
                        .display-3
                          = customer.get_package_price
                        
                                              
  .row.mt-5                    
    .col-sm-12        
      .card
        .card-header
          .h2.mt-4
            Receivng 
        .card-body
          .row    
            .col-sm-12
              .form-group
                = form.label "Date"
                = form.date_field :receiving_date, class: "form-control"
          .row  
            .col-sm-6
              .form-group
                = form.label "Receipt Book"
                = form.collection_select :receipt_book_id, customer&.staff&.receipt_books&.where(status: "Assigned"), :id, :book_number, {prompt: true}, class: "form-control"
          
            .col-sm-6
              .form-group
                = form.label "Receipt Book Pages"
                = form.collection_select :receipt_book_page_id, ReceiptBookPage.all, :id, :page_no, {prompt: true}, class: "form-control"
          
          .row
            .col-sm-6
              .form-group
                = form.label "Amount Received"
                = form.number_field :amount_received, class: "form-control", placeholder: "Enter Received Amount"
                = form.hidden_field :amount, value: customer.get_package_price
            .col-sm-6
              .form-group
                = form.label "Discount"
                = form.number_field :discount, class: "form-control", placeholder: "Enter Discounted Amount"
          .row
            .col-sm-6
              .form-group
                = form.label "Staff Name"
                = form.text_field :full_name, class: "form-control readonly_field", readonly: true, value: "#{customer&.staff&.full_name if customer&.staff&.present?}"
                = form.hidden_field :staff_id, value: customer&.staff&.id           
                = form.hidden_field :customer_id, value: customer&.id           
            .col-sm-6
              .form-group
                = form.label "Remaining Due"
                = form.text_field :balance, class: "form-control readonly_field", readonly: true, value: "" 
                = form.hidden_field :status, value: true
        .card-footer  
          .actions
            = form.submit class: "btn btn-primary"
      
    
      - if customer&.receivings&.present?
        = render 'customer_billing', customer: customer
  

app/views/app/receivings/_search.html.haml
-# = search_form_for q do |f|
-#   .input-group.input-group-flush.input-group-merge.input-group-reverse
-#     = f.search_field :name_cont, class: 'form-control list-search', placeholder: 'Search'
-#     %span.input-group-text
-#       %i.fe.fe-search
                              

app/views/app/receivings/edit.html.haml
.header
  .container-fluid
    .header-body
      .row.align-items-end
        .col
          %h6.header-pretitle
            Overview
          %h1.header-title
            Edit Company

.container-fluid   
  .row
    .col-12.col-lg-6.col-xl
      .card
        .card-body
          = render 'form', company: @company
             

app/views/app/receivings/index.html.haml
.container-fluid
  .row.justify-content-center
    .col-12
      / Header
      .header
        .header-body
          .row.align-items-center
            .col
              / Pretitle
              %h6.header-pretitle
                Overview
              / Title
              %h1.header-title
                Receivings
            .col-auto
              / Button
              = link_to 'New Receiving', search_customer_receivings_path, class: "btn btn-outline-primary lift"        
          
      .card
        .card-header
          / Search
          = render "search", q: @q
          
          / Dropdown
          -# .dropdown
          -#   %button#bulkActionDropdown.btn.btn-sm.btn-white.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :type => "button"}
          -#     Bulk action
          -#   .dropdown-menu.dropdown-menu-end{"aria-labelledby" => "bulkActionDropdown"}
          -#     %a.dropdown-item{:href => "#!"} Action
          -#     %a.dropdown-item{:href => "#!"} Another action
          -#     %a.dropdown-item{:href => "#!"} Something else here
        .table-responsive
          %table.table.table-sm.table-nowrap.card-table
            - if @receivings.any?
              %thead
                %tr
                  %th #
                  %th Staff
                  %th Customer
                  %th Amount
                  %th Balance
                  %th Receiving Date
                  %th Book Number
                  %th Book's Page Number
                  %th Service
              %tbody.list
                - @receivings.each.with_index(1) do |receiving, index|
                  %tr
                    %td= index
                    %td= receiving.staff.full_name
                    %td= receiving.customer.name
                    %td= receiving.amount_received
                    %td= receiving.balance
                    %td= receiving.receiving_date
                    %td= receiving.receipt_book.book_number
                    %td= receiving.receipt_book_page.page_no
                    %td= receiving&.customer&.service&.name
                    %td.text-right
                      -# = link_to 'Edit', edit_company_path(company), class: "btn btn-outline-info btn-sm"
            - else
              = render 'shared/no_data'
  .row        
    = paginate @receivings     
     

app/views/app/receivings/new.html.haml
.header
  .container-fluid
    .header-body
      .row.align-items-end
        .col
          %h6.header-pretitle
            Overview
          %h1.header-title
            #{ params['term'].present? ? 'First Receiving' : 'New Receiving' }

.container-fluid   
  .row
    .col-sm-12
      = render 'form', receiving: @receiving, customer: @customer
             

app/views/app/receivings/search_customer.html.haml
-# .row
-#   .col-sm-4
-#     .form-group
-#       = number_field_tag 'customer_id', "#{params['customer_id'].present? ? params['customer_id'] : nil}", class: "form-control", id: 'search_customer_id', placeholder: "Enter Customer ID"
-#   .col-sm-2
-#     .form-group
-#       = button_tag 'Search', type: "button", class: "btn btn-primary", id: "search_button" 

.container-fluid
  .row.justify-content-center
    .col-12
      / Header
      .header
        .header-body
          .row.align-items-center
            .col
              / Pretitle
              %h6.header-pretitle
                Overview
              / Title
              %h1.header-title
                Search Customer
                  
      .card
        .card-body
          = search_form_for @q, url: search_customer_receivings_path do |f|
            .row
              .col-sm-2
                = f.label "Customer ID"
                = f.search_field :id_eq, placeholder: "Enter Customer ID", class: "form-control"
                 
              .col-sm-2
                = f.label "House No"
                = f.search_field :house_no_cont, class: "form-control", placeholder: "Enter House No"
              
              .col-sm-2
                = f.label "Area"
                = f.select :area_id_eq, Area.all.map { |area| [area.name, area.id] }, { include_blank: "Select Area" }, { class: 'form-control' } 
              
              .col-sm-2
                = f.label "Username"
                = f.search_field :username_cont, class: "form-control", placeholder: "Enter Username"
              
              .col-sm-2
                = f.label "All Search"
                = f.search_field :id_or_old_ref_no_or_name_or_father_name_or_cnic_or_mobile_primary_or_mobile_secondary_or_service_name, class: "form-control", placeholder: "Enter Search Keyword"
              
              .col-sm-2
                = submit_tag "Search", class: "btn w-100 btn-outline-primary mt-4"
        
      
      .card
        .card-body
          .table-responsive
            %table.table.table-sm.table-nowrap.card-table
              - if @customers.any?
                %thead
                  %tr
                    %th ID
                    %th Name
                    %th House No#
                    %th Area
                    %th Username
                    %th Mobile
                    %th Pon No#
                    %th Monthly Fee
                    %th Balance Month
                    %th Amnount
                    %th Action
                %tbody.list
                  - @customers.each.with_index(1) do |customer|
                    %tr
                      %td= customer&.id
                      %td= customer&.name
                      %td= customer&.house_no
                      %td= customer&.area&.name
                      %td= customer&.username
                      %td= customer&.mobile_primary
                      %td= customer&.pon_no
                      %td= customer&.package&.price
                      %td= customer&.receivings&.last&.balance || 0
                      %td= customer&.package&.price.to_i + customer&.receivings&.last&.balance.to_i 
                      %td.text-right
                        = link_to 'Proceed', "#{new_receiving_path}?customer_id=#{customer.id}", class: "btn btn-outline-info btn-sm"
              - else
                = render 'shared/no_data'
  