config/routes.rb
require('sidekiq/web')

Rails.application.routes.draw do
  default_url_options host: ENV['ASSET_PATH']
  
  #Sidekiq Routes
  mount Sidekiq::Web => '/sidekiq'
  
  #Swagger Routes
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # Admin Devise Routes
  devise_for :admins, controllers: {
    registrations: 'app/admins/registrations',
    passwords: 'app/admins/passwords',
    confirmations: 'app/admins/confirmations'
  }

  devise_scope :admin do
    authenticated :admin do
      root 'app/dashboards#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # API Routes
  scope '/api' do
    scope '/v1' do
      use_doorkeeper do
        controllers tokens: 'api/v1/tokens'
      end
    end
  end

  scope module: :api, path: 'api' do
    scope module: :v1, path: 'v1' do
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
        passwords: 'api/v1/users/passwords',
        confirmations: 'api/v1/users/confirmations'
      }, scoped_views: 'api/v1/users'
    end
  end

  # APP Routes
  scope module: :app, path: 'app' do
    resource :dashboard, only: [:show]
    resource :additional_payments, only: [:new, :create]
    resources :countries
    resources :cities
    resources :areas
    resources :sub_areas do
      collection do
        get :get_sub_areas
      end
    end
    resources :staffs do
      collection do
        get :archived
        get :check_username
      end
      member do
        get :restore
      end
    end
    resources :payments
    resources :receipt_books do
      collection do
        get :book_pages
      end
    end
    resources :message_templates
    resources :messages
    resources :companies

    resources :purchase_packages do
      collection do
        get :purchase_packages_list
      end
    end
    
    resources :packages do
      collection do
        get :customer_package_list
      end
    end
    resources :customers do 
      collection do
        get :check_username
        get :export_profile
        get :export_billings
      end
      member do
        get :settings
        get :deactivate
        get :activate
      end
      resources :subscriptions do
        collection do
          get :expire
        end
      end
    end
    
    resources :receivings do
      collection do
        get :search_customer
      end
    end
  end

  # root to: 'home#index'
end

app/models/staff.rb
class Staff < ApplicationRecord
  acts_as_paranoid
  
  validates :full_name, presence: true
  validates :staff_type_id, presence: true
  validates :starting_salary, presence: true
  validates :current_salary, presence: true
  
  belongs_to :staff_type
  belongs_to :blood_group
  
  has_many :payments
  has_many :receipt_books
  
  has_many :customers
  has_many :receivings
  
  after_create :register_staff
  
  def register_staff
    return if self.username.empty?
    
    username = self.username
    email = "#{username}@skynet.com"
    password = self.password
   
    staff = Admin.create!(username: username, email: email, password: password)
    
    staff.add_role :staff 
  end
end

app/models/staff_type.rb
class StaffType < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  
  has_many :staff
end

app/controllers/app/staffs_controller.rb
module App
  class StaffsController < ApplicationController
    before_action :set_staff, only: %i[show edit update destroy restore]
    
    def index
      @q = Staff.ransack(params[:q])
      @staffs = @q.result.page(params[:page]).per(10)
    end
    
    def new
      @staff = Staff.new
    end
    
    def create
      @staff = Staff.new(staff_params)
      if @staff.save!
        redirect_to staffs_path, notice: 'Staff was successfully created'
      else
        render 'new', alert: 'Something went wrong'
      end
    end
    
    def show; end
    
    def edit; end
    
    def update
      if @staff.update(staff_params)
        redirect_to staffs_path, notice: 'Staff was successfully updated'
      else
        render 'edit', alert: 'Something went wrong';
      end
    end
    
    def destroy
      if @staff.destroy
        redirect_to staffs_path, info: 'Staff was successfully deleted'
      end
    end
    
    def archived
      @staffs = Staff.only_deleted
    end
    
    def restore
      @staff = Staff.only_deleted.where(id: params[:id]).first
      if @staff.restore
        redirect_to staffs_path, notice: 'Staff was successfully restored'
      end
    end
    
    def check_username
      username = Staff.where(username: params['username']).any?
      render json: { data: username }
    end
    
    private
    
    def staff_params
      params.require(:staff).permit(:staff_type_id, :blood_group_id, :full_name, :father_name, :dob, :cnic, :mobile_primary, :mobile_secondary, :address, :remarks, :joining, :starting_salary, :current_salary, :official_mobile_no, :official_mobile_model, :official_moterbike_no, :others, :username, :password)
    end
    
    def set_staff
      @staff = Staff.find_by(id: params[:id])
    end
  end
end

app/helpers/app/staffs_helper.rb
module App::StaffsHelper
end

app/views/app/staffs/_basic_profile.html.haml
.row
  .col-sm-4          
    .card
      / Body
      .card-body
        / Image
        %img.staff-img.rounded-circle.border.border-4.border-card{:alt => "...", :src => "/img/icons/employee.png"}/
        / Heading
        %h2.card-title.text-center
          = staff&.full_name
        / Badges
        %p.text-center.mb-4
          %span.badge.bg-danger-soft
            Blood Group:
            = staff&.blood_group.name
        
        / List group
        .list-group.list-group-flush.mb-4
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Type
              .col-auto
                / Time
                %time.small.text-muted
                  = staff&.staff_type.name
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Joined
              .col-auto
                / Time
                %time.small.text-muted{:datetime => "1988-10-24"}
                  = staff&.joining.strftime("%d-%B-%Y")
            / / .row
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small CNIC
              .col-auto
                / Text
                %small.text-muted
                  = staff&.cnic
            / / .row
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Date of Birth
              .col-auto
                / Link
                %a.small.text-muted
                  = staff&.dob
            / / .row
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Mobile (Primary)
              .col-auto
                / Text
                %small.text-muted
                  = staff&.mobile_primary
            / / .row
  .col-sm-8          
    .card
      / Body
      .card-body
        
        / List group
        .list-group.list-group-flush.mb-4
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Mobile (Secondary)
              .col-auto
                / Link
                %a.small.text-muted
                  = staff&.mobile_secondary  
          / / .row
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Starting Salary
              .col-auto
                / Link
                %a.small.text-muted
                  = staff&.starting_salary
                  
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Current Salary
              .col-auto
                / Text
                %small.text-muted
                  = staff&.current_salary
            / / .row
            
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Official Mobile No
              .col-auto
                / Text
                %small.text-muted
                  = staff&.official_mobile_no
            / / .row
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Official Mobile Model
              .col-auto
                / Link
                %a.small.text-muted
                  = staff&.official_mobile_model
          
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Official Motorbike No
              .col-auto
                / Link
                %a.small.text-muted
                  = staff&.official_moterbike_no            
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Address
              .col-auto
                / Time
                %time.small.text-muted{:datetime => "1988-10-24"}
                  = staff&.address
            / / .row
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Remarks
              .col-auto
                / Text
                %small.text-muted
                  = staff&.remarks
            / / .row
        
          .list-group-item
            .row.align-items-center
              .col
                / Title
                %small Others
              .col-auto
                / Link
                %a.small.text-muted
                  = staff&.others           

app/views/app/staffs/_form.html.haml
= form_with(model: staff) do |form|
  - if staff.errors.any?
    #error_explanation  
      - staff.errors.full_messages.each do |message|
        .col
          .alert.alert-danger.text-white
            = message
  .row
    .col-sm-12
      .card
        .card-header
          %h4.card-title-header Staff Type
        .card-body        
          .form-group
            = form.label "Select Type"
            = form.collection_select :staff_type_id, StaffType.all, :id, :name, {prompt: true}, class: "form-control", required: true
  .row
    .col-sm-12
      .card
        .card-header
          %h4.card-title-header Basic Information
        .card-body   
          .row
            .col-sm-6    
              .form-group
                = form.label :full_name
                = form.text_field :full_name, class: "form-control"
            .col-sm-6    
              .form-group
                = form.label :father_name
                = form.text_field :father_name, class: "form-control"
          
          .row
            .col-sm-6    
              .form-group
                = form.label "Date of Birth"
                = form.date_field :dob, class: "form-control"
            .col-sm-6    
              .form-group
                = form.label :cnic
                = form.text_field :cnic, class: "form-control"      
          
          .row
            .col-sm-6    
              .form-group
                = form.label "Mobile (Primary)"
                = form.text_field :mobile_primary, class: "form-control"
            .col-sm-6    
              .form-group
                = form.label "Mobile (Secondary)"
                = form.text_field :mobile_secondary, class: "form-control"
          
          .row
            .col-sm-6    
              .form-group
                = form.label :address
                = form.text_area :address, class: "form-control", rows: 4, cols: 10
            .col-sm-6    
              .form-group
                = form.label :remarks
                = form.text_area :remarks, class: "form-control", rows: 4, cols: 10
                          
  .row
    .col-sm-12
      .card
        .card-header
          %h4.card-title-header Blood Group
        .card-body        
          .form-group
            = form.label "Select Blood Group"
            = form.collection_select :blood_group_id, BloodGroup.all, :id, :name, {prompt: true}, class: "form-control", required: true
  
  .row
    .col-sm-12
      .card
        .card-header
          %h4.card-title-header Job Information
        .card-body
          .row
            .col-sm-6    
              .form-group
                = form.label :joining
                = form.date_field :joining, class: "form-control"
            .col-sm-6    
              .form-group
                = form.label :starting_salary
                = form.number_field :starting_salary, class: "form-control", min: 0
          
          .row
            .col-sm-6    
              .form-group
                = form.label :current_salary
                = form.number_field :current_salary, class: "form-control", min: 0
            .col-sm-6    
              .form-group
                = form.label :official_mobile_no
                = form.text_field :official_mobile_no, class: "form-control"
          
          .row
            .col-sm-6    
              .form-group
                = form.label :official_mobile_model
                = form.text_field :official_mobile_model, class: "form-control"
            .col-sm-6    
              .form-group
                = form.label :official_moterbike_no
                = form.text_field :official_moterbike_no, class: "form-control"
  
  .row
    .col-sm-12
      .card
        .card-header
          %h4.card-title-header Credentials
        .card-body
          .row
            .col-sm-12   
              .form-group
                - if request.fullpath.include?('edit')
                  = form.label 'Username ( No Space)'
                  = form.text_field :username, class: "form-control readonly_field", readonly: true
                  %span.text-danger#username_error
                - else 
                  = form.label 'Username ( No Space)'
                  = form.text_field :username, class: "form-control"
                  %span.text-danger#username_error
          .row
            .col-sm-12   
              .form-group
                - if request.fullpath.include?('edit')
                  = form.label :password
                  = form.text_field :password, class: "form-control readonly_field", readonly: true
                - else 
                  = form.label :password
                  = form.text_field :password, class: "form-control"
                
  .row
    .col-sm-12
      .card
        .card-header
          %h4.card-title-header Other Information
        .card-body
          .row
            .col-sm-12   
              .form-group
                = form.label :others
                = form.text_area :others, class: "form-control", rows: 4, cols: 10
  .actions
    = form.submit class: "btn btn-primary"

app/views/app/staffs/_payments.html.haml
.row.justify-content-md-center
  .col-12
    .card.custome-height
      .card-header
        %h1.header-title
          Payments
      .card-body
        %table.table.table-sm#several
          - if staff.payments.any?  
            %thead
              %tr
                %th{scope: "col"} #
                %th{scope: "col"} Date
                %th{scope: "col"} Payment Mode
                %th{scope: "col"} Purpose
                %th{scope: "col"} Amount
                %th{scope: "col"} Reason

            %tbody
              - staff.payments.each.with_index(1) do |payment, index|
                %tr
                  %td= index
                  %td= payment.date.strftime("%d-%B- %Y")
                  %td= payment.payment_mode
                  %td= payment.purpose
                  %td= payment.amount
                  %td= payment.reason
                                       
          - else
            = render 'shared/no_data'

app/views/app/staffs/_receipt_books.html.haml
.row.justify-content-md-center
  .col-12
    .card.custome-height
      .card-header
        %h1.header-title
          Receipt Books
      .card-body
        %table.table.table-sm#several
          - if staff.receipt_books.any?  
            %thead
              %tr
                %th{scope: "col"} #
                %th{scope: "col"} Issue Date
                %th{scope: "col"} Book No
                %th{scope: "col"} From
                %th{scope: "col"} To
                %th{scope: "col"} Total Pages
                %th{scope: "col"} Collection
                %th{scope: "col"} Blank Pages
                %th{scope: "col"} Status

            %tbody
              - staff.receipt_books.each.with_index(1) do |book, index|
                %tr
                  %td= index
                  %td= book.issue_date.strftime("%d-%B- %Y")
                  %td= book.book_number
                  %td= book.from
                  %td= book.to
                  %td= book.receipt_book_pages.count
                  %td= book.receipt_book_pages.sum(:amount)
                  %td= book.receipt_book_pages.map {|c| c.amount.zero?}.count(true)
                  %td= book.status
                                       
          - else
            = render 'shared/no_data'

app/views/app/staffs/_search.html.haml
= search_form_for q do |f|
  .input-group.input-group-flush.input-group-merge.input-group-reverse
    = f.search_field :full_name_or_mobile_primary_or_staff_type_name_or_blood_group_name_cont, class: 'form-control list-search', placeholder: 'Search'
    %span.input-group-text
      %i.fe.fe-search
                    

app/views/app/staffs/archived.html.haml
.header
  .container-fluid
    .header-body
      .row.align-items-end
        .col
          %h1.header-title
            Archived Staff
        .col-auto  
.container-fluid
  .row.justify-content-md-center
    .col-12
      .card
        .card-body
          %table.table.table-sm
            - if @staffs.any?  
              %thead
                %tr
                  %th{scope: "col"} #
                  %th{scope: "col"} Type
                  %th{scope: "col"} Name
                  %th{scope: "col"} Father Name
                  %th{scope: "col"} Mobile
                  %th{scope: "col"} Current Salary
                  %th{scope: "col"} Bloog Group
                  %th{scope: "col"} Deleted At
                  %th{scope: "col"} Action
              %tbody
                - @staffs.each.with_index(1) do |staff, index|
                  %tr
                    %td= index
                    %td= staff.staff_type.name
                    %td= staff.full_name
                    %td= staff.father_name
                    %td= staff.mobile_primary
                    %td= staff.current_salary
                    %td= staff.blood_group.name
                    %td= staff.deleted_at.strftime("%d-%B-%Y")
                    %td.text-right
                      = link_to 'Restore', restore_staff_path(staff), class: "btn btn-outline-info btn-sm", data: { confirm: "Are you Sure?" }
            - else
              = render 'shared/no_data'
             

app/views/app/staffs/edit.html.haml
.header
  .container-fluid
    .header-body
      .row.align-items-end
        .col
          %h6.header-pretitle
            Overview
          %h1.header-title
            Edit Staff

.container-fluid   
  .row
    .col-12.col-lg-6.col-xl
      = render 'form', staff: @staff, readonly: true
             

app/views/app/staffs/index.html.haml
.container-fluid
  .row.justify-content-center
    .col-12
      / Header
      .header
        .header-body
          .row.align-items-center
            .col
              / Pretitle
              %h6.header-pretitle
                Overview
              / Title
              %h1.header-title
                Staff
            .col-auto
              / Button
              = link_to 'New Staff', new_staff_path, class: "btn btn-outline-primary lift"        
          / / .row
          -# .row.align-items-center
          -#   .col
          -#     / Nav
          -#     %ul.nav.nav-tabs.nav-overflow.header-tabs
          -#       %li.nav-item
          -#         %a.nav-link.active{:href => "#!"}
          -#           All
          -#           %span.badge.rounded-pill.bg-secondary-soft 823
          -#       %li.nav-item
          -#         %a.nav-link{:href => "#!"}
          -#           Pending
          -#           %span.badge.rounded-pill.bg-secondary-soft 24
          -#       %li.nav-item
          -#         %a.nav-link{:href => "#!"}
          -#           Processing
          -#           %span.badge.rounded-pill.bg-secondary-soft 3
          -#       %li.nav-item
          -#         %a.nav-link{:href => "#!"}
          -#           Refunded
          -#           %span.badge.rounded-pill.bg-secondary-soft 71
      / Card
      .card{"data-list" => "{\"valueNames\": [\"orders-order\", \"orders-product\", \"orders-date\", \"orders-total\", \"orders-status\", \"orders-method\"]}"}
        .card-header
          / Search
          = render "search", q: @q
          
          / Dropdown
          -# .dropdown
          -#   %button#bulkActionDropdown.btn.btn-sm.btn-white.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :type => "button"}
          -#     Bulk action
          -#   .dropdown-menu.dropdown-menu-end{"aria-labelledby" => "bulkActionDropdown"}
          -#     %a.dropdown-item{:href => "#!"} Action
          -#     %a.dropdown-item{:href => "#!"} Another action
          -#     %a.dropdown-item{:href => "#!"} Something else here
        .table-responsive
          %table.table.table-sm.table-nowrap.card-table
            - if @staffs.any?
              %thead
                %tr
                  %th #
                  %th Type
                  %th Name
                  %th Father Name
                  %th Mobile
                  %th Current Salary
                  %th Bloog Group
                  %th Action
              %tbody.list
                - @staffs.each.with_index(1) do |staff, index|
                  %tr
                    %td= index
                    %td= staff.staff_type.name
                    %td= staff.full_name
                    %td= staff.father_name
                    %td= staff.mobile_primary
                    %td= staff.current_salary
                    %td= staff.blood_group.name
                    %td.text-right
                      = link_to 'View', staff_path(staff), class: "btn btn-outline-success btn-sm"
                      = link_to 'Edit', edit_staff_path(staff), class: "btn btn-outline-info btn-sm"
                      = link_to "Delete", staff, method: :delete, data: { confirm: "Are you Sure?" }, class: "btn btn-outline-danger btn-sm"
            - else
              = render 'shared/no_data'
  .row        
    = paginate @staffs     
                       

app/views/app/staffs/new.html.haml
.header
  .container-fluid
    .header-body
      .row.align-items-end
        .col
          %h6.header-pretitle
            Overview
          %h1.header-title
            New Staff

.container-fluid   
  .row
    .col-sm-12
      = render 'form', staff: @staff
             

app/views/app/staffs/show.html.haml
.header
  .container-fluid
    .header-body
      .row.align-items-end
        .col
          %h1.header-title
            Staff Detail
                 
.container-fluid
  = render "basic_profile", staff: @staff
  = render "payments", staff: @staff
  = render "receipt_books", staff: @staff